
python3 set_up_run_folder.py



RUNS=2
MODEL="any"
ANS=0
RT=-0.75
LF=1.2
BOLDSCALE=0.75
NEGBOLDSCALE=1
BOLDEXP=6
NEGBOLDEXP=15
BOLDPOSITIVE=1
BOLDNEGATIVE=0
VERBOSE=nil

ccl64 -n -l run_direct.lisp -- $RUNS $MODEL $ANS $RT $LF $BOLDSCALE $NEGBOLDSCALE $BOLDEXP $NEGBOLDEXP $BOLDPOSITIVE $BOLDNEGATIVE $VERBOSE


python3 evaluate.py