
python3 run_set_up_run_folder.py



RUNS=10
MODEL="any"
ANS=0.5
RT=-0.65
LF=0.4
BOLDSCALE=1
NEGBOLDSCALE=1
BOLDEXP=5
NEGBOLDEXP=15
BOLDPOSITIVE=6
BOLDNEGATIVE=1
VERBOSE=t


ccl64 -n -l run_direct.lisp -- $RUNS $MODEL $ANS $RT $LF $BOLDSCALE $NEGBOLDSCALE $BOLDEXP $NEGBOLDEXP $BOLDPOSITIVE $BOLDNEGATIVE $VERBOSE

python3 run_evaluate.py

